services:
  - type: web
    name: pk-corporate-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    envVars:
      - key: PORT
        value: 9090
      - key: DB_URL
        fromDatabase:
          name: pk-corporate-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: pk-corporate-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: pk-corporate-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRY
        value: 900000
      - key: JWT_REFRESH_EXPIRY
        value: 604800000
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: MAX_FILE_SIZE
        value: 10MB
      - key: FRONTEND_URL
        value: https://frontend-phi-lemon-czqwlgh8ug.vercel.app
      - key: MAX_REQUEST_SIZE
        value: 20MB

databases:
  - name: pk-corporate-db
    plan: free
    databaseName: pk_corporate
    user: pk_corporate_user
